language: python
sudo: required
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
matrix:
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"
install:
  - pip install poetry
  - poetry develop
script:
  - py.test
