env:
  global:
    - CC_TEST_REPORTER_ID=2609815ad1c6d2d807e761812030b6d8ae9e0e52cdb58315ab2a57067dc4a1c6
language: python
sudo: required
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
matrix:
  include:
    - { python: "3.7", env: TESTENV=lint }
    - { python: "3.7", env: TESTENV=examples }
  allow_failures:
    - python: "3.7-dev"
    - python: "3.8-dev"
    - python: "nightly"

install:
  - pip install -e '.[dev]'

before_script:
  - ./scripts/pre-build.sh

script:
  - ./scripts/build.sh

after_script:
  - ./scripts/post-build.sh
